### ISSUE TITLE
TODO: Complete the documentation, add link to thesis

### ISSUE THREAD

**Issue by brunoklaus** [brunoklaus/GSSL_label_noise#2]
- [ ] Polish the documentation of each module's methods
- [ ] Include an overview of the project's modules in the README.md
- [ ] Add link to master's thesis "Analysis of Label Noise in Graph-Based Semi-Supervised Learning"
